[package]
name = "uu_truncate"
version = "0.0.30"
authors = ["uutils developers"]
license = "MIT"
description = "truncate ~ (uutils) truncate (or extend) FILE to SIZE"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/main/src/uu/truncate"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2024"

readme.workspace = true

[lints]
workspace = true

[lib]
path = "src/truncate.rs"

[dependencies]
clap = { workspace = true }
uucore = { workspace = true, features = ["parser"] }

[[bin]]
name = "truncate"
path = "src/main.rs"
